# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    new_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

new_controller:
  ros__parameters:
    joints:
      - j_phantomx_attachment
      - j_c1_lf
      - j_c2_lf
      - j_thigh_lf
      - j_tibia_lf
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity